const SAVE_KEY = '365_canvas_road_runner_v2';

const ROUTES = {
  track: { label: '365 Test Track', profile: 'track', length: 9800, meters: 3200, reward: 1.05, skyA: '#7ddcff', skyB: '#d9fbff', grass: '#58b957', road: '#2d3748', seed: 4 },
  barangay: { label: 'Barangay Route', profile: 'barangay', length: 10800, meters: 3500, reward: 1, skyA: '#8bdcff', skyB: '#e1fbff', grass: '#5fbf57', road: '#3a4555', seed: 1 },
  farm: { label: 'Farm Supply Run', profile: 'farm', length: 11800, meters: 3900, reward: 1.15, skyA: '#9ee8ff', skyB: '#e7fcff', grass: '#66bd45', road: '#554537', seed: 3 },
  mountain: { label: 'Mountain Parts Run', profile: 'mountain', length: 13800, meters: 4600, reward: 1.25, skyA: '#86d4ff', skyB: '#e0f7ff', grass: '#4f9e52', road: '#39414d', seed: 2 },
  port: { label: 'Port Export Route', profile: 'port', length: 15000, meters: 5000, reward: 1.35, skyA: '#93dfff', skyB: '#e4fbff', grass: '#49a985', road: '#36414d', seed: 5 }
};

const GHOST_MODES = { solo: { label: 'Solo', count: 0 }, ghost2: { label: '1 Ghost', count: 1 }, ghost3: { label: '2 Ghosts', count: 2 }, ghost4: { label: '3 Ghosts', count: 3 } };
const VEHICLES = {
  hatchback: { label: 'Starter Hatchback', asset: 'hatchback', unlock: { coins: 0, parts: 0 }, speed: 1, accel: 1, fuel: 1, handling: 1, durability: 1, description: 'Balanced starter car.' },
  greenCompact: { label: 'Compact Sport', asset: 'greenCompact', unlock: { coins: 180, parts: 1 }, speed: 1.08, accel: 1.08, fuel: .96, handling: 1.05, durability: .95, description: 'Faster compact for early ghost runs.' },
  pickup: { label: 'Parts Pickup', asset: 'pickup', unlock: { coins: 360, parts: 3 }, speed: .96, accel: .95, fuel: 1.2, handling: 1.08, durability: 1.22, description: 'Longer range and better stability.' },
  serviceVan: { label: 'Service Van', asset: 'serviceVan', unlock: { coins: 720, parts: 6 }, speed: .92, accel: .9, fuel: 1.35, handling: 1.04, durability: 1.35, description: 'Endurance vehicle for long routes.' },
  offroad: { label: 'Off-Road Truck', asset: 'offroad', unlock: { coins: 1100, parts: 10 }, speed: 1, accel: 1, fuel: 1.18, handling: 1.32, durability: 1.45, description: 'Best for mountain and rough routes.' },
  race: { label: 'Purple Race Coupe', asset: 'race', unlock: { coins: 1450, parts: 12 }, speed: 1.24, accel: 1.18, fuel: .9, handling: 1.08, durability: .85, description: 'Fastest track vehicle.' }
};
const UPGRADES = {
  engine: { label: 'Engine', description: 'More acceleration.', max: 15, baseCoins: 45, baseParts: 0, growth: 1.42, partsEvery: 4 },
  tires: { label: 'Tires', description: 'Higher speed and less drag.', max: 15, baseCoins: 40, baseParts: 0, growth: 1.4, partsEvery: 3 },
  fuelTank: { label: 'Fuel Tank', description: 'More fuel range and station capacity.', max: 15, baseCoins: 55, baseParts: 0, growth: 1.45, partsEvery: 3 },
  suspension: { label: 'Suspension', description: 'Better hill movement and less wear.', max: 15, baseCoins: 45, baseParts: 0, growth: 1.42, partsEvery: 3 },
  durability: { label: 'Durability', description: 'Reduces wear and tear damage.', max: 15, baseCoins: 60, baseParts: 1, growth: 1.5, partsEvery: 2 }
};
const ASSET_PATHS = {
  hatchback: '/assets/vehicles/car-compact-blue.svg', greenCompact: '/assets/vehicles/car-compact-green.svg', pickup: '/assets/vehicles/pickup-orange.svg', serviceVan: '/assets/vehicles/van-service-white.svg', offroad: '/assets/vehicles/offroad-red.svg', race: '/assets/vehicles/race-purple.svg',
  ghostA: '/assets/vehicles/car-compact-green.svg', ghostB: '/assets/vehicles/pickup-orange.svg', ghostC: '/assets/vehicles/van-service-white.svg',
  coin: '/assets/road-runner/token-coin.svg', energy: '/assets/road-runner/token-energy.svg', parts: '/assets/road-runner/token-parts.svg', fuelStation: '/assets/road-runner/fuel-station.svg', partsStore: '/assets/road-runner/parts-store.svg', wreck: '/assets/road-runner/wrecked-car.svg'
};
let canvas = null, ctx = null, frameId = 0, mountedScreen = null, activeRoute = 'track', activeGhostMode = 'ghost2', saveData = loadSave(), images = loadImages(), input = { gas: false, brake: false }, game = null, lastTime = 0;

function defaultUpgrades(){ return { engine:1, tires:1, fuelTank:1, suspension:1, durability:1 }; }
function migrateUpgrades(u = {}){ return { engine: u.engine || 1, tires: u.tires || 1, fuelTank: u.fuelTank || u.energyTank || 1, suspension: u.suspension || 1, durability: u.durability || 1 }; }
function normUpgrades(u={}){ const m=migrateUpgrades(u), r={}; Object.keys(defaultUpgrades()).forEach(k=>r[k]=Math.max(1,Math.min(UPGRADES[k].max,Number(m[k]||1)))); return r; }
function loadSave(){ try{ const p=JSON.parse(localStorage.getItem(SAVE_KEY)||localStorage.getItem('365_canvas_road_runner_v1')||'{}'); const unlocked=Array.isArray(p.unlockedVehicles)&&p.unlockedVehicles.length?p.unlockedVehicles:['hatchback']; const selected=unlocked.includes(p.selectedVehicle)?p.selectedVehicle:'hatchback'; return { coins:p.coins||0, parts:p.parts||0, bestDistance:p.bestDistance||0, bestTrail:Array.isArray(p.bestTrail)?p.bestTrail:[], upgrades:normUpgrades(p.upgrades), unlockedVehicles:unlocked, selectedVehicle:selected, lifetimeFuel:p.lifetimeFuel||0, lifetimeWear:p.lifetimeWear||0 }; }catch{ return { coins:0, parts:0, bestDistance:0, bestTrail:[], upgrades:defaultUpgrades(), unlockedVehicles:['hatchback'], selectedVehicle:'hatchback', lifetimeFuel:0, lifetimeWear:0 }; } }
function saveGameData(){ localStorage.setItem(SAVE_KEY,JSON.stringify(saveData)); }
function fmt(v){ if(v>=1000000)return`${(v/1000000).toFixed(1)}M`; if(v>=1000)return`${(v/1000).toFixed(1)}K`; return`${Math.floor(v)}`; }
function upgradeCost(k,l){ const i=UPGRADES[k]; if(!i||l>=i.max)return{coins:Infinity,parts:Infinity}; return { coins:Math.round(i.baseCoins*Math.pow(i.growth,l-1)), parts:i.baseParts+Math.floor(l/i.partsEvery) }; }
function selectedVehicle(){ return VEHICLES[saveData.selectedVehicle]||VEHICLES.hatchback; }
function vehicleStats(){ const u=normUpgrades(saveData.upgrades), v=selectedVehicle(); return { acceleration:(82+u.engine*8)*v.accel, topSpeed:(132+u.tires*6)*v.speed, drag:Math.max(3,11-u.tires*.35), maxFuel:(95+u.fuelTank*20)*v.fuel, fuelUse:Math.max(1.6,4.0-u.fuelTank*.08), handling:(.08+u.suspension*.014)*v.handling, spring:4.8+u.suspension*.42, damping:2.7+u.suspension*.18, durability:(1+u.durability*.1)*v.durability, wearLimit:100+u.durability*12 }; }
function routeMeters(route,pixels){ return Math.floor(Math.max(0,pixels)*(route.meters/route.length)); }
function routeY(route,x,h){ const base=Math.max(170,Math.min(h-130,h*.61)),s=route.seed||1; if(route.profile==='track')return base+Math.sin((x+s*90)/430)*14+Math.sin((x+s*40)/190)*6+Math.sin((x+s*20)/820)*16; if(route.profile==='mountain')return base+Math.sin((x+s*160)/180)*42+Math.sin((x+s*85)/74)*13-Math.sin((x+s*60)/520)*46; if(route.profile==='farm')return base+Math.sin((x+s*120)/240)*26+Math.sin((x+s*70)/96)*10-Math.sin((x+s*30)/680)*22; if(route.profile==='port')return base+Math.sin((x+s*110)/360)*20+Math.sin((x+s*55)/155)*7-Math.sin((x+s*40)/940)*24; return base+Math.sin((x+s*120)/175)*24+Math.sin((x+s*70)/78)*9-Math.sin((x+s*30)/540)*26; }
function routeAngle(route,x,h){ const rise=routeY(route,x+8,h)-routeY(route,x-8,h); return Math.max(-.55,Math.min(.55,(rise/16)*.42)); }
function loadImages(){ const r={}; Object.entries(ASSET_PATHS).forEach(([k,p])=>{const img=new Image(); img.onload=()=>{img.ready=true}; img.onerror=()=>{img.ready=false}; img.src=p; r[k]=img;}); return r; }
function makePickups(route){ const pickups=[], spacing=route.profile==='track'?250:215; for(let x=320;x<route.length-260;x+=spacing){ const type=x%(spacing*6)===0?'energy':x%(spacing*4)===0?'parts':'coin'; pickups.push({x,type,collected:false}); } return pickups; }
function makeCheckpoints(route){ const items=[]; for(let x=1150;x<route.length-600;x+=1850)items.push({x,type:'fuelStation',used:false}); for(let x=1750;x<route.length-700;x+=2500)items.push({x,type:'partsStore',used:false}); for(let x=900;x<route.length-500;x+=1650)items.push({x,type:'wreck',used:false}); return items.sort((a,b)=>a.x-b.x); }
function resetRun(){ const route=ROUTES[activeRoute], stats=vehicleStats(); game={route,stats,x:80,speed:0,fuel:stats.maxFuel,distancePx:0,distanceM:0,coins:0,parts:0,wear:0,pitch:0,pitchVel:0,suspensionTravel:0,elapsed:0,finished:false,pickups:makePickups(route),checkpoints:makeCheckpoints(route),samples:[],lastSample:0,message:'',eventText:'',eventTimer:0,ghostColors:['#22c55e','#f97316','#e5e7eb']}; updateHud(); }
function setText(sel,val){ const e=document.querySelector(sel); if(e)e.textContent=val; }
function shellHtml(){ return `<section class="card roadRunnerShell"><div class="roadRunnerHeader"><h2>365 Hill Route - Checkpoint Systems</h2><p>Fuel stations, parts stores, wreck pickups, wear-and-tear, and softer suspension movement.</p></div><div class="roadRunnerHud"><div class="roadRunnerStat"><b data-rr-distance>0m</b><span>Distance</span></div><div class="roadRunnerStat"><b data-rr-fuel>100%</b><span>Fuel</span></div><div class="roadRunnerStat"><b data-rr-wear>0%</b><span>Wear</span></div><div class="roadRunnerStat"><b data-rr-coins>${fmt(saveData.coins)}</b><span>Coins</span></div><div class="roadRunnerStat"><b data-rr-parts>${fmt(saveData.parts)}</b><span>Parts</span></div><div class="roadRunnerStat"><b data-rr-best>${fmt(saveData.bestDistance)}m</b><span>Best</span></div></div><div class="roadRunnerQuickPanel"><button class="btn primary" onclick="window.restartHillRoute?.()">Restart Run</button><div class="roadRunnerVs" data-rr-vs></div><div class="roadRunnerLegend"><span><i class="coin"></i>Coins</span><span><i class="energy"></i>Fuel</span><span><i class="parts"></i>Parts</span></div></div><div class="roadRunnerGameFrame"><div id="roadRunnerGameHost"><canvas id="roadRunnerCanvas"></canvas></div><div class="roadRunnerOverlay"><div class="roadRunnerBadge" data-rr-route>${ROUTES[activeRoute].label}</div><div class="roadRunnerBadge" data-rr-mode>${GHOST_MODES[activeGhostMode].label}</div></div><div class="roadRunnerControlHint">Drive past fuel stations to refuel. Parts stores and wrecks add parts. Wear rises on rough hits.</div><div class="roadRunnerControls"><button class="roadRunnerPedal brake" data-rr-control="brake">BRAKE</button><button class="roadRunnerPedal gas" data-rr-control="gas">GAS</button></div></div><section class="roadRunnerPanel"><div class="roadRunnerPanelTitle"><h3>Ghost Race</h3><span class="roadRunnerNotice">Computer ghosts or saved best trail.</span></div><div class="roadRunnerModeGrid">${Object.entries(GHOST_MODES).map(([k,v])=>`<button class="btn ${k===activeGhostMode?'primary':'ghost'}" onclick="window.setHillGhosts?.('${k}')">${v.label}</button>`).join('')}</div></section><section class="roadRunnerPanel"><div class="roadRunnerPanelTitle"><h3>Routes</h3><span class="roadRunnerNotice">Track is easiest. Mountain and Port are endurance routes.</span></div><div class="roadRunnerModeGrid">${Object.entries(ROUTES).map(([k,v])=>`<button class="btn ${k===activeRoute?'gold':'ghost'}" onclick="window.setHillRoute?.('${k}')">${v.label}</button>`).join('')}</div></section><section class="roadRunnerPanel" data-road-runner-vehicles></section><section class="roadRunnerPanel" data-road-runner-garage></section></section>`; }
function updateHud(){ if(!game)return; setText('[data-rr-distance]',`${Math.floor(game.distanceM)}m`); setText('[data-rr-fuel]',`${Math.max(0,Math.floor(game.fuel/game.stats.maxFuel*100))}%`); setText('[data-rr-wear]',`${Math.floor(Math.min(100,game.wear/game.stats.wearLimit*100))}%`); setText('[data-rr-coins]',fmt(saveData.coins)); setText('[data-rr-parts]',fmt(saveData.parts)); setText('[data-rr-best]',`${fmt(saveData.bestDistance)}m`); setText('[data-rr-route]',ROUTES[activeRoute].label); setText('[data-rr-mode]',GHOST_MODES[activeGhostMode].label); setText('[data-rr-vs]',`You: ${selectedVehicle().label} | Opponent: ${activeGhostMode==='solo'?'None':saveData.bestTrail.length?'Your Best Ghost':'Computer Ghosts'}`); renderVehiclePanel(); renderGaragePanel(); }
function renderVehiclePanel(){ const p=document.querySelector('[data-road-runner-vehicles]'); if(!p)return; p.innerHTML=`<div class="roadRunnerPanelTitle"><h3>Vehicle Selection</h3><span class="roadRunnerNotice">Different vehicles change speed, fuel, handling, and durability.</span></div><div class="roadRunnerVehicleGrid">${Object.entries(VEHICLES).map(([k,i])=>vehicleCard(k,i)).join('')}</div>`; }
function vehicleCard(k,i){ const unlocked=saveData.unlockedVehicles.includes(k), selected=saveData.selectedVehicle===k, can=saveData.coins>=i.unlock.coins&&saveData.parts>=i.unlock.parts, action=unlocked?`window.selectRoadRunnerVehicle?.('${k}')`:`window.unlockRoadRunnerVehicle?.('${k}')`, img=ASSET_PATHS[i.asset]; return `<div class="roadRunnerVehicleCard ${selected?'selected':''}"><div class="vehicleThumb">${img?`<img src="${img}" alt="${i.label}"/>`:''}</div><h4>${i.label}</h4><p>${i.description}</p><div class="vehicleStats">SPD ${i.speed.toFixed(2)} • FUEL ${i.fuel.toFixed(2)} • DUR ${i.durability.toFixed(2)}</div><button class="btn ${selected?'gold':unlocked||can?'primary':'ghost'}" ${selected||(!unlocked&&!can)?'disabled':''} onclick="${action}">${selected?'Selected':unlocked?'Select':can?`Unlock ${fmt(i.unlock.coins)}C / ${i.unlock.parts}P`:`Locked ${fmt(i.unlock.coins)}C / ${i.unlock.parts}P`}</button></div>`; }
function renderGaragePanel(){ const p=document.querySelector('[data-road-runner-garage]'); if(!p)return; p.innerHTML=`<div class="roadRunnerPanelTitle"><h3>Garage Upgrades</h3><span class="roadRunnerNotice">Upgrade fuel range, suspension, and durability for longer runs.</span></div><div class="roadRunnerWalletRow"><div class="roadRunnerWalletPill">Coins: ${fmt(saveData.coins)}</div><div class="roadRunnerWalletPill">Parts: ${fmt(saveData.parts)}</div></div><div class="roadRunnerGarageGrid">${Object.entries(UPGRADES).map(([k,i])=>upgradeCard(k,i)).join('')}</div>`; }
function upgradeCard(k,i){ const l=saveData.upgrades[k]||1, max=l>=i.max, c=upgradeCost(k,l), can=!max&&saveData.coins>=c.coins&&saveData.parts>=c.parts; return `<div class="roadRunnerUpgradeCard"><h4>${i.label} Lv.${l}</h4><p>${i.description}</p><div class="roadRunnerUpgradeMeta"><span>${max?'Max':`Next Lv.${l+1}`}</span><span>${max?'MAX':`${fmt(c.coins)} coins - ${c.parts} parts`}</span></div><button class="btn ${can?'primary':'ghost'}" ${can?'':'disabled'} onclick="window.buyRoadRunnerUpgrade?.('${k}')">${max?'Maxed':'Upgrade'}</button></div>`; }
function draw(){ if(!canvas||!ctx||!game)return; const w=canvas.width,h=canvas.height,r=game.route,cam=Math.max(0,Math.min(r.length-w+260,game.x-w*.34)); drawBackground(w,h,r,cam); drawRoad(w,h,r,cam); drawCheckpoints(w,h,r,cam); drawPickups(w,h,r,cam); drawGhosts(w,h,r,cam); drawPlayer(w,h,r,cam); drawFinish(w,h,r,cam); drawRunMeters(w,h); if(game.finished)drawFinishMessage(w,h); }
function drawBackground(w,h,r,cam){ const sky=ctx.createLinearGradient(0,0,0,h); sky.addColorStop(0,r.skyA); sky.addColorStop(.58,r.skyB); sky.addColorStop(.59,r.grass); sky.addColorStop(1,'#2f8f3f'); ctx.fillStyle=sky; ctx.fillRect(0,0,w,h); for(let wx=Math.floor(cam/520)*520-200;wx<cam+w+520;wx+=520){ctx.globalAlpha=.7;ctx.fillStyle='#fff';roundedCloud(wx-cam,52+(wx%110));ctx.globalAlpha=1;} }
function roundedCloud(x,y){ctx.beginPath();ctx.arc(x,y+8,22,0,Math.PI*2);ctx.arc(x+26,y,28,0,Math.PI*2);ctx.arc(x+58,y+10,20,0,Math.PI*2);ctx.fill();}
function drawRoad(w,h,r,cam){ const start=Math.max(0,cam-80),end=Math.min(r.length+260,cam+w+140); ctx.fillStyle=r.grass;ctx.beginPath();ctx.moveTo(0,h);for(let wx=start;wx<=end;wx+=18)ctx.lineTo(wx-cam,routeY(r,wx,h)+38);ctx.lineTo(end-cam,h);ctx.closePath();ctx.fill();ctx.strokeStyle=r.road;ctx.lineWidth=r.profile==='track'?34:28;ctx.lineCap='round';ctx.lineJoin='round';ctx.beginPath();for(let wx=start;wx<=end;wx+=14){const x=wx-cam,y=routeY(r,wx,h);if(wx===start)ctx.moveTo(x,y);else ctx.lineTo(x,y);}ctx.stroke();ctx.strokeStyle='rgba(248,250,252,.62)';ctx.lineWidth=4;for(let wx=Math.floor(start/120)*120;wx<=end;wx+=120){ctx.beginPath();ctx.moveTo(wx-cam,routeY(r,wx,h)-1);ctx.lineTo(wx+58-cam,routeY(r,wx+58,h)-1);ctx.stroke();}}
function drawCheckpoints(w,h,r,cam){ for(const item of game.checkpoints){const x=item.x-cam;if(x<-110||x>w+110)continue;const y=routeY(r,item.x,h)-76;const img=images[item.type]; if(img?.ready)ctx.drawImage(img,x-42,y-34,84,68);else{ctx.fillStyle=item.type==='fuelStation'?'#22c55e':item.type==='partsStore'?'#f97316':'#94a3b8';ctx.fillRect(x-34,y-24,68,48);} ctx.fillStyle='#fff';ctx.font='900 10px Arial';ctx.textAlign='center';ctx.strokeStyle='#000';ctx.lineWidth=3;const label=item.type==='fuelStation'?'FUEL STOP':item.type==='partsStore'?'PARTS STORE':'SALVAGE';ctx.strokeText(item.used?'USED':label,x,y-40);ctx.fillText(item.used?'USED':label,x,y-40);} }
function drawPickups(w,h,r,cam){ for(const p of game.pickups){ if(p.collected)continue;const x=p.x-cam;if(x<-60||x>w+60)continue;const y=routeY(r,p.x,h)-34,img=images[p.type]; if(img?.ready)ctx.drawImage(img,x-20,y-20,40,40);else{ctx.fillStyle=p.type==='energy'?'#38bdf8':p.type==='parts'?'#a78bfa':'#facc15';ctx.beginPath();ctx.arc(x,y,17,0,Math.PI*2);ctx.fill();} } }
function drawGhosts(w,h,r,cam){ const mode=GHOST_MODES[activeGhostMode],keys=['ghostA','ghostB','ghostC']; for(let i=0;i<mode.count;i++){const p=ghostPoint(i,h),x=p.x-cam;if(x<-100||x>w+120)continue;drawCar(x,p.y,routeAngle(r,p.x,h)*.65,images[keys[i]],i===0&&saveData.bestTrail.length?'Best Ghost':`Computer ${i+1}`,.5,game.ghostColors[i]);} }
function ghostPoint(i,h){ const r=game.route; if(i===0&&saveData.bestTrail.length>5){const target=Math.max(0,game.elapsed-i*.8);let s=saveData.bestTrail[saveData.bestTrail.length-1];for(const item of saveData.bestTrail){if(item.t>=target){s=item;break;}}return{x:s.x,y:routeY(r,s.x,h)-30};} const pace=.9+i*.08,x=80+Math.max(0,game.elapsed-i*.75)*(game.stats.topSpeed*pace*.58);return{x,y:routeY(r,x,h)-30}; }
function drawPlayer(w,h,r,cam){ const x=game.x-cam,y=routeY(r,game.x,h)-30,angle=game.pitch; drawCar(x,y,angle,images[selectedVehicle().asset],'You',1,'#3b82f6'); }
function drawCar(x,y,angle,img,label,alpha,color){ctx.save();ctx.translate(x,y);ctx.rotate(angle);ctx.globalAlpha=alpha;ctx.fillStyle='rgba(0,0,0,.22)';ctx.beginPath();ctx.ellipse(0,22,48,10,0,0,Math.PI*2);ctx.fill(); if(img?.ready)ctx.drawImage(img,-56,-31,112,56);else{ctx.fillStyle=color;roundRect(-36,-15,72,30,9);ctx.fill();ctx.strokeStyle='#172033';ctx.lineWidth=3;ctx.stroke();} ctx.strokeStyle='#111827';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(-28,18+game.suspensionTravel);ctx.lineTo(-28,30);ctx.moveTo(28,18-game.suspensionTravel);ctx.lineTo(28,30);ctx.stroke();ctx.restore();ctx.globalAlpha=alpha;ctx.fillStyle='#fff';ctx.font='900 11px Arial';ctx.textAlign='center';ctx.strokeStyle='#000';ctx.lineWidth=3;ctx.strokeText(label,x,y-46);ctx.fillText(label,x,y-46);ctx.globalAlpha=1;}
function roundRect(x,y,w,h,r){ctx.beginPath();ctx.moveTo(x+r,y);ctx.lineTo(x+w-r,y);ctx.quadraticCurveTo(x+w,y,x+w,y+r);ctx.lineTo(x+w,y+h-r);ctx.quadraticCurveTo(x+w,y+h,x+w-r,y+h);ctx.lineTo(x+r,y+h);ctx.quadraticCurveTo(x,y+h,x,y+h-r);ctx.lineTo(x,y+r);ctx.quadraticCurveTo(x,y,x+r,y);}
function drawFinish(w,h,r,cam){const x=r.length-cam;if(x<-20||x>w+30)return;const y=routeY(r,r.length,h);ctx.fillStyle='#fff';ctx.fillRect(x-5,y-70,10,90);ctx.fillStyle='#111827';for(let i=0;i<6;i++)ctx.fillRect(x-5+(i%2)*5,y-70+i*10,5,10);}
function drawRunMeters(w,h){ const fuelPct=game.fuel/game.stats.maxFuel,wearPct=Math.min(1,game.wear/game.stats.wearLimit); drawBar(14,42,150,11,'Fuel',fuelPct,'#22c55e'); drawBar(14,58,150,11,'Wear',wearPct,wearPct>.75?'#ef4444':'#f59e0b'); ctx.fillStyle='rgba(4,17,29,.75)';roundRect(14,74,220,28,14);ctx.fill();ctx.fillStyle='#fff';ctx.font='900 11px Arial';ctx.fillText(`Run +${game.coins} coins  +${game.parts} parts`,28,93); if(game.eventTimer>0){ctx.fillStyle='#fff';ctx.font='900 16px Arial';ctx.textAlign='center';ctx.strokeStyle='#000';ctx.lineWidth=4;ctx.strokeText(game.eventText,w/2,82);ctx.fillText(game.eventText,w/2,82);} }
function drawBar(x,y,w,h,label,p,color){ctx.fillStyle='rgba(4,17,29,.72)';roundRect(x,y,w,h,6);ctx.fill();ctx.fillStyle=color;roundRect(x,y,w*Math.max(0,Math.min(1,p)),h,6);ctx.fill();ctx.fillStyle='#fff';ctx.font='800 9px Arial';ctx.textAlign='left';ctx.fillText(label,x+w+6,y+9);}
function drawFinishMessage(w,h){ctx.fillStyle='rgba(4,17,29,.88)';roundRect(w/2-150,h/2-52,300,104,18);ctx.fill();ctx.fillStyle='#fff';ctx.font='900 16px Arial';ctx.textAlign='center';ctx.fillText(game.message,w/2,h/2-8);ctx.font='800 12px Arial';ctx.fillText('Tap Restart Run to run again.',w/2,h/2+18);}
function triggerEvent(text){game.eventText=text;game.eventTimer=1.2;}
function update(dt){ if(!game||game.finished)return; const h=canvas.height,route=game.route,target=routeAngle(route,game.x,h),rough=Math.abs(target-game.pitch),dur=game.stats.durability; if(input.gas&&game.fuel>0){game.speed+=game.stats.acceleration*dt;game.fuel-=game.stats.fuelUse*dt;} if(input.brake)game.speed-=170*dt;game.speed-=game.stats.drag*dt;game.speed=Math.max(0,Math.min(game.stats.topSpeed,game.speed));game.x+=game.speed*dt;game.distancePx=Math.max(0,game.x-80);game.distanceM=routeMeters(route,game.distancePx);game.pitchVel+=(target-game.pitch)*game.stats.spring*dt;game.pitchVel-=game.pitchVel*game.stats.damping*dt;game.pitch+=game.pitchVel*dt;game.suspensionTravel=Math.sin(game.elapsed*18)*Math.min(6,game.speed/38)+target*6;game.wear+=(rough*game.speed*.018+Math.max(0,game.speed-game.stats.topSpeed*.86)*.002)*dt*60/dur;collectPickupsAndCheckpoints(); if(game.elapsed-game.lastSample>.18){game.samples.push({t:Number(game.elapsed.toFixed(2)),x:Math.round(game.x)});game.lastSample=game.elapsed;} if(game.eventTimer>0)game.eventTimer-=dt; if(game.fuel<=0||game.wear>=game.stats.wearLimit||game.distancePx>=game.route.length)finishRun(game.distancePx>=game.route.length); updateHud(); }
function collectPickupsAndCheckpoints(){ for(const p of game.pickups){if(p.collected||Math.abs(game.x-p.x)>42)continue;p.collected=true;if(p.type==='energy'){game.fuel=Math.min(game.stats.maxFuel+24,game.fuel+16);saveData.lifetimeFuel+=16;triggerEvent('Fuel +');}if(p.type==='parts'){game.parts+=1;saveData.parts+=1;triggerEvent('Part +1');}if(p.type==='coin'){const c=Math.round(4*game.route.reward);game.coins+=c;saveData.coins+=c;}saveGameData();} for(const c of game.checkpoints){if(c.used||Math.abs(game.x-c.x)>65)continue;c.used=true;if(c.type==='fuelStation'){game.fuel=Math.min(game.stats.maxFuel+36,game.fuel+game.stats.maxFuel*.42);saveData.lifetimeFuel+=Math.floor(game.stats.maxFuel*.42);triggerEvent('Fuel Station + Range');}if(c.type==='partsStore'){game.parts+=3;saveData.parts+=3;triggerEvent('Auto Parts +3');}if(c.type==='wreck'){game.parts+=2;saveData.parts+=2;game.wear=Math.max(0,game.wear-8);triggerEvent('Salvage +2 Parts');}saveGameData();} }
function finishRun(completed){game.finished=true;const bonus=Math.floor(game.distanceM/75);saveData.coins+=bonus;saveData.parts+=game.parts;saveData.lifetimeWear+=Math.floor(game.wear);if(game.distanceM>saveData.bestDistance){saveData.bestDistance=Math.floor(game.distanceM);saveData.bestTrail=game.samples.slice(-520);}saveGameData();game.message=completed?`Route complete +${bonus} bonus coins`:game.wear>=game.stats.wearLimit?`Worn out at ${Math.floor(game.distanceM)}m`:`Out of fuel at ${Math.floor(game.distanceM)}m`;updateHud();}
function loop(t){if(!document.querySelector('#screen-race.active .roadRunnerShell')){frameId=requestAnimationFrame(loop);return;}const dt=Math.min((t-lastTime)/1000||.016,.05);lastTime=t;if(game){game.elapsed+=dt;update(dt);draw();}frameId=requestAnimationFrame(loop);}
function resizeCanvas(){if(!canvas)return;const host=document.querySelector('#roadRunnerGameHost');if(!host)return;const rect=host.getBoundingClientRect(),w=Math.max(320,Math.floor(rect.width||420)),h=Math.max(320,Math.floor(rect.height||340));canvas.width=w;canvas.height=h;canvas.style.width=`${w}px`;canvas.style.height=`${h}px`;}
function bindControls(){document.querySelectorAll('[data-rr-control]').forEach(btn=>{const control=btn.getAttribute('data-rr-control');const set=(v,e)=>{e?.preventDefault();if(control==='gas')input.gas=v;if(control==='brake')input.brake=v;btn.classList.toggle('active',v);};btn.addEventListener('pointerdown',e=>{btn.setPointerCapture?.(e.pointerId);set(true,e);},{passive:false});btn.addEventListener('pointerup',e=>set(false,e),{passive:false});btn.addEventListener('pointercancel',e=>set(false,e),{passive:false});btn.addEventListener('pointerleave',e=>set(false,e),{passive:false});});window.onkeydown=e=>{if(!document.querySelector('#screen-race.active'))return;if(e.key==='ArrowRight'||e.key.toLowerCase()==='d')input.gas=true;if(e.key==='ArrowLeft'||e.key.toLowerCase()==='a')input.brake=true;};window.onkeyup=e=>{if(e.key==='ArrowRight'||e.key.toLowerCase()==='d')input.gas=false;if(e.key==='ArrowLeft'||e.key.toLowerCase()==='a')input.brake=false;};}
function mountRoadRunner(force=false){const screen=document.querySelector('#screen-race.active');if(!screen)return;if(force||screen!==mountedScreen||!screen.querySelector('.roadRunnerShell')){saveData=loadSave();screen.innerHTML=shellHtml();mountedScreen=screen;canvas=screen.querySelector('#roadRunnerCanvas');ctx=canvas.getContext('2d');bindControls();resizeCanvas();resetRun();renderVehiclePanel();renderGaragePanel();draw();}if(!frameId){lastTime=performance.now();frameId=requestAnimationFrame(loop);}}
window.restartHillRoute=()=>{input.gas=false;input.brake=false;resetRun();draw();};window.setHillGhosts=m=>{if(!GHOST_MODES[m])return;activeGhostMode=m;mountRoadRunner(true);};window.setHillRoute=r=>{if(!ROUTES[r])return;activeRoute=r;mountRoadRunner(true);};window.selectRoadRunnerVehicle=k=>{if(!saveData.unlockedVehicles.includes(k))return;saveData.selectedVehicle=k;saveGameData();resetRun();renderVehiclePanel();updateHud();draw();};window.unlockRoadRunnerVehicle=k=>{const item=VEHICLES[k];if(!item||saveData.unlockedVehicles.includes(k))return;if(saveData.coins<item.unlock.coins||saveData.parts<item.unlock.parts)return;saveData.coins-=item.unlock.coins;saveData.parts-=item.unlock.parts;saveData.unlockedVehicles.push(k);saveData.selectedVehicle=k;saveGameData();resetRun();renderVehiclePanel();updateHud();draw();};window.buyRoadRunnerUpgrade=k=>{const l=saveData.upgrades[k]||1,item=UPGRADES[k];if(!item||l>=item.max)return;const c=upgradeCost(k,l);if(saveData.coins<c.coins||saveData.parts<c.parts)return;saveData.coins-=c.coins;saveData.parts-=c.parts;saveData.upgrades[k]=l+1;saveGameData();renderGaragePanel();resetRun();updateHud();draw();};
function inject(){const screen=document.querySelector('#screen-race.active');if(!screen)return;requestAnimationFrame(()=>mountRoadRunner(false));}
window.addEventListener('resize',()=>{resizeCanvas();draw();});const observer=new MutationObserver(()=>inject());observer.observe(document.documentElement,{childList:true,subtree:true,attributes:true,attributeFilter:['class']});window.addEventListener('load',inject);document.addEventListener('click',()=>requestAnimationFrame(inject));
