const originalUrl = '/src/ui/roadRunnerRuntimeV6.js?v=stable-v4';

const ROUTES_PATCH = `const ROUTES = {
  track:{label:'PH: Barangay Test Loop',profile:'barangay',length:9800,meters:3200,reward:1.05,difficulty:.75,skyA:'#7ddcff',skyB:'#d9fbff',grass:'#58b957',road:'#2d3748',seed:4,unlock:0},japan:{label:'Japan: Touge Night Run',profile:'mountain',length:11200,meters:3600,reward:1.12,difficulty:1,skyA:'#9ed8ff',skyB:'#f5d0fe',grass:'#4f9e52',road:'#303847',seed:11,unlock:450},china:{label:'China: Great Wall Ridge',profile:'mountain',length:12400,meters:4050,reward:1.18,difficulty:1.12,skyA:'#93c5fd',skyB:'#fde68a',grass:'#6b8e3d',road:'#3f3f46',seed:21,unlock:900},thailand:{label:'Thailand: Market Coast',profile:'barangay',length:10800,meters:3500,reward:1.10,difficulty:.95,skyA:'#8bdcff',skyB:'#fed7aa',grass:'#65a30d',road:'#475569',seed:31,unlock:1300},india:{label:'India: Monsoon Highway',profile:'farm',length:11800,meters:3900,reward:1.18,difficulty:1.12,skyA:'#7dd3fc',skyB:'#c7d2fe',grass:'#84cc16',road:'#4b5563',seed:41,unlock:1800},uae:{label:'UAE: Desert Express',profile:'port',length:12600,meters:4200,reward:1.22,difficulty:1.18,skyA:'#93c5fd',skyB:'#fde68a',grass:'#d6a85c',road:'#3f3f46',seed:51,unlock:2300},egypt:{label:'Egypt: Nile Desert Run',profile:'port',length:13200,meters:4400,reward:1.25,difficulty:1.22,skyA:'#bae6fd',skyB:'#fef3c7',grass:'#c2a24a',road:'#44403c',seed:61,unlock:2900},italy:{label:'Italy: Coastal Sprint',profile:'track',length:11600,meters:3800,reward:1.20,difficulty:1.05,skyA:'#7dd3fc',skyB:'#dbeafe',grass:'#22c55e',road:'#334155',seed:71,unlock:3500},usa:{label:'USA: Route 365 Highway',profile:'track',length:14200,meters:4700,reward:1.30,difficulty:1.25,skyA:'#60a5fa',skyB:'#e0f2fe',grass:'#4ade80',road:'#1f2937',seed:81,unlock:4300},brazil:{label:'Brazil: Rainforest Rally',profile:'farm',length:15000,meters:5000,reward:1.38,difficulty:1.38,skyA:'#67e8f9',skyB:'#bbf7d0',grass:'#16a34a',road:'#3f3f46',seed:91,unlock:5200}
};`;

const VEHICLES_PATCH = `const VEHICLES = {
  hatchback:{label:'Starter Hatchback',asset:'hatchback',unlock:{coins:0,parts:0},speed:1,accel:1,fuel:1,handling:1,durability:1,description:'Balanced starter car.'},greenCompact:{label:'Compact Sport',asset:'greenCompact',unlock:{coins:180,parts:1},speed:1.08,accel:1.08,fuel:.96,handling:1.05,durability:.95,description:'Cheap early speed upgrade.'},cityTaxi:{label:'City Taxi',asset:'cityTaxi',unlock:{coins:260,parts:2},speed:1.03,accel:1.12,fuel:1.05,handling:1.12,durability:.98,description:'Quick launch and good control.'},pickup:{label:'Parts Pickup',asset:'pickup',unlock:{coins:420,parts:4},speed:.96,accel:.95,fuel:1.2,handling:1.08,durability:1.22,description:'Carries more fuel and survives longer.'},rallyLite:{label:'Rally Lite',asset:'rallyLite',unlock:{coins:640,parts:6},speed:1.06,accel:1.10,fuel:1.02,handling:1.28,durability:1.14,description:'Great first rough-road car.'},serviceVan:{label:'Service Van',asset:'serviceVan',unlock:{coins:820,parts:8},speed:.92,accel:.90,fuel:1.35,handling:1.04,durability:1.35,description:'Endurance route vehicle.'},desertRunner:{label:'Desert Runner',asset:'desertRunner',unlock:{coins:1050,parts:11},speed:1.02,accel:1.02,fuel:1.28,handling:1.18,durability:1.34,description:'Built for desert maps.'},offroad:{label:'Off-Road Truck',asset:'offroad',unlock:{coins:1300,parts:14},speed:1,accel:1,fuel:1.18,handling:1.36,durability:1.52,description:'Best for rough roads and potholes.'},exportVan:{label:'Export Support Van',asset:'exportVan',unlock:{coins:1650,parts:18},speed:.94,accel:.94,fuel:1.5,handling:1.08,durability:1.55,description:'Long-distance support vehicle.'},race:{label:'Purple Race Coupe',asset:'race',unlock:{coins:2050,parts:22},speed:1.24,accel:1.18,fuel:.90,handling:1.08,durability:.85,description:'Fastest early track vehicle.'},mountainCourier:{label:'Mountain Courier',asset:'mountainCourier',unlock:{coins:2600,parts:28},speed:1.10,accel:1.08,fuel:1.18,handling:1.42,durability:1.38,description:'Strong hill climbing and stable handling.'},superCoupe:{label:'365 Super Coupe',asset:'superCoupe',unlock:{coins:3400,parts:36},speed:1.38,accel:1.28,fuel:.86,handling:1.16,durability:.92,description:'High speed endgame coupe.'}
};`;

const ASSETS_PATCH = `const ASSET_PATHS = {
  hatchback:'/assets/vehicles/racer/sprite_0000.png',greenCompact:'/assets/vehicles/racer/sprite_0010.png',cityTaxi:'/assets/vehicles/racer/sprite_0002.png',pickup:'/assets/vehicles/racer/sprite_0011.png',rallyLite:'/assets/vehicles/racer/sprite_0012.png',serviceVan:'/assets/vehicles/racer/sprite_0007.png',desertRunner:'/assets/vehicles/racer/sprite_0015.png',offroad:'/assets/vehicles/racer/sprite_0006.png',exportVan:'/assets/vehicles/racer/sprite_0013.png',race:'/assets/vehicles/racer/sprite_0005.png',mountainCourier:'/assets/vehicles/racer/sprite_0014.png',superCoupe:'/assets/vehicles/racer/sprite_0009.png',ghostA:'/assets/vehicles/racer/sprite_0010.png',ghostB:'/assets/vehicles/racer/sprite_0011.png',ghostC:'/assets/vehicles/racer/sprite_0007.png',coin:'/assets/road-runner/token-coin.svg',fuel:'/assets/road-runner/token-energy.svg',parts:'/assets/road-runner/token-parts.svg',tools:'/assets/road-runner/tool-kit.svg',fuelStation:'/assets/road-runner/fuel-station.svg',partsStore:'/assets/road-runner/parts-store.svg',mechanicShop:'/assets/road-runner/mechanic-shop.svg',wreck:'/assets/road-runner/wrecked-car.svg'
};`;

const VEHICLE_CARD_PATCH = `function vehicleCard(key,item){const unlocked=saveData.unlockedVehicles.includes(key);const selected=saveData.selectedVehicle===key;const canUnlock=saveData.coins>=item.unlock.coins&&saveData.parts>=item.unlock.parts;const action=unlocked?'window.selectRoadRunnerVehicle?.(\\''+key+'\\')':'window.unlockRoadRunnerVehicle?.(\\''+key+'\\')';const img=ASSET_PATHS[item.asset];const note=!unlocked&&!canUnlock?'<div class="rrWhyLocked">Need '+formatSmall(Math.max(0,item.unlock.coins-saveData.coins))+' coins / '+Math.max(0,item.unlock.parts-saveData.parts)+' parts</div>':'';return '<div class="roadRunnerVehicleCard '+(selected?'selected':'')+'"><div class="vehicleThumb">'+(img?'<img src="'+img+'" alt="'+item.label+'"/>':'')+'</div><h4>'+item.label+'</h4><p>'+item.description+'</p><div class="vehicleStats">SPD '+item.speed.toFixed(2)+' • FUEL '+item.fuel.toFixed(2)+' • DUR '+item.durability.toFixed(2)+'</div><button class="btn '+(selected?'gold':unlocked||canUnlock?'primary':'ghost')+'" onclick="'+action+'">'+(selected?'Selected':unlocked?'Select':canUnlock?'Unlock '+formatSmall(item.unlock.coins)+'C / '+item.unlock.parts+'P':'Unlock unavailable')+'</button>'+note+'</div>'}`;

const ACTIONS_PATCH = `function rrNotice(text){let n=document.querySelector('.rrProgressToast');if(!n){n=document.createElement('div');n.className='rrProgressToast';document.body.appendChild(n)}n.textContent=text;n.classList.add('show');clearTimeout(n._t);n._t=setTimeout(()=>n.classList.remove('show'),2200)}
window.selectRoadRunnerVehicle=function(key){if(!saveData.unlockedVehicles.includes(key)){rrNotice('Vehicle locked. Unlock it first.');return}saveData.selectedVehicle=key;saveGameData();resetRun();renderVehiclePanel();updateHud();draw();rrNotice('Vehicle selected.')};
window.unlockRoadRunnerVehicle=function(key){const item=VEHICLES[key];if(!item){rrNotice('Vehicle not found.');return}if(saveData.unlockedVehicles.includes(key)){window.selectRoadRunnerVehicle(key);return}if(saveData.coins<item.unlock.coins||saveData.parts<item.unlock.parts){rrNotice('Cannot unlock: Need '+formatSmall(Math.max(0,item.unlock.coins-saveData.coins))+' coins / '+Math.max(0,item.unlock.parts-saveData.parts)+' parts');return}saveData.coins-=item.unlock.coins;saveData.parts-=item.unlock.parts;saveData.unlockedVehicles.push(key);saveData.selectedVehicle=key;saveGameData();resetRun();renderVehiclePanel();updateHud();draw();rrNotice('Vehicle unlocked and selected.')};
window.buyRoadRunnerUpgrade=function(key){const level=saveData.upgrades[key]||1;const item=UPGRADES[key];if(!item){rrNotice('Upgrade not found.');return}if(level>=item.max){rrNotice(item.label+' is maxed.');return}const cost=upgradeCost(key,level);if(saveData.coins<cost.coins||saveData.parts<cost.parts){rrNotice('Cannot upgrade: Need '+formatSmall(Math.max(0,cost.coins-saveData.coins))+' coins / '+Math.max(0,cost.parts-saveData.parts)+' parts');return}saveData.coins-=cost.coins;saveData.parts-=cost.parts;saveData.upgrades[key]=level+1;saveGameData();renderGaragePanel();resetRun();updateHud();draw();rrNotice(item.label+' upgraded to Lv.'+(level+1)+'.')};`;

function replaceBlock(source,start,endToken,replacement){const a=source.indexOf(start);const b=source.indexOf(endToken,a);if(a<0||b<0)return{source,ok:false};return{source:source.slice(0,a)+replacement+source.slice(b),ok:true}}
function replaceFunction(source,name,replacement,nextName){return replaceBlock(source,'function '+name,'\nfunction '+nextName,replacement)}
function patch(source){let r=replaceBlock(source,'const ROUTES = {','\n\nconst GHOST_MODES',ROUTES_PATCH),s=r.source;let v=replaceBlock(s,'const VEHICLES = {','\n\nconst UPGRADES',VEHICLES_PATCH);s=v.source;let a=replaceBlock(s,'const ASSET_PATHS = {','\n\nlet canvas',ASSETS_PATCH);s=a.source;let vc=replaceFunction(s,'vehicleCard(key, item)',VEHICLE_CARD_PATCH,'renderGaragePanel()');s=vc.source;let ac=replaceBlock(s,'window.selectRoadRunnerVehicle = (key) => {','\n\nfunction inject()',ACTIONS_PATCH);s=ac.source;return{source:s,routes:r.ok,vehicles:v.ok,assets:a.ok,vehicleCard:vc.ok,actions:ac.ok}}
async function load(){const res=await fetch(originalUrl,{cache:'no-store'});if(!res.ok)throw new Error('runtime '+res.status);const source=await res.text();const out=patch(source);const blob=new Blob([out.source],{type:'text/javascript'});await import(URL.createObjectURL(blob));console.info('[365 Racer] V4 runtime loaded',out)}
load().catch(e=>{console.error('[365 Racer] V4 runtime failed. Loading base V6.',e);import(originalUrl)});
