const KEY='365_canvas_road_runner_v4';
let filter='all';
function load(){try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch{return{}}}
function save(s){localStorage.setItem(KEY,JSON.stringify(s))}
function up0(){return{engine:1,tires:1,fuelTank:1,suspension:1,durability:1,transmission:1,brakes:1,repairKit:1}}
function msg(t){let e=document.querySelector('.rrProgressToast');if(!e){e=document.createElement('div');e.className='rrProgressToast';document.body.appendChild(e)}e.textContent=t;e.classList.add('show');clearTimeout(e._t);e._t=setTimeout(()=>e.classList.remove('show'),2200)}
function keyFrom(btn){return (btn?.getAttribute('onclick')||'').match(/'([^']+)'/)?.[1]||btn?.dataset?.key||''}
function costFrom(text){const nums=[...String(text||'').matchAll(/(\d+(?:\.\d+)?)(K|M)?\s*([CP])/gi)];let coins=0,parts=0;for(const m of nums){let n=Number(m[1]);if(m[2]==='K')n*=1000;if(m[2]==='M')n*=1000000;if(m[3].toUpperCase()==='C')coins=Math.round(n);if(m[3].toUpperCase()==='P')parts=Math.round(n)}return{coins,parts}}
function missing(c,s){const mc=Math.max(0,c.coins-(s.coins||0));const mp=Math.max(0,c.parts-(s.parts||0));return mc||mp?`Need ${mc} coins / ${mp} parts`:''}
function refresh(){window.restartHillRoute?.();setTimeout(()=>document.dispatchEvent(new Event('click')),80)}
function vehicleClass(card){const t=(card.textContent||'').toLowerCase();if(t.includes('race')||t.includes('coupe'))return'race';if(t.includes('off-road')||t.includes('rally')||t.includes('mountain'))return'offroad';if(t.includes('pickup'))return'utility';if(t.includes('van')||t.includes('desert')||t.includes('export')||t.includes('service'))return'endurance';return'starter'}
function ensureFilters(panel){if(panel.querySelector('.rrV3Filters'))return;const row=document.createElement('div');row.className='rrV3Filters rrVehicleFilters';row.innerHTML=['all:All','starter:Starter','utility:Utility','offroad:Off-Road','race:Race','endurance:Endurance'].map(x=>{const[a,b]=x.split(':');return`<button type="button" data-f="${a}">${b}</button>`}).join('');panel.insertBefore(row,panel.querySelector('.roadRunnerVehicleGrid'));row.addEventListener('click',e=>{const b=e.target.closest('[data-f]');if(!b)return;filter=b.dataset.f;applyFilter(panel)})}
function applyFilter(panel){panel.querySelectorAll('[data-f]').forEach(b=>b.classList.toggle('active',b.dataset.f===filter));panel.querySelectorAll('.roadRunnerVehicleCard').forEach(c=>{const cls=vehicleClass(c);c.dataset.vehicleClass=cls;c.style.display=filter==='all'||filter===cls?'':'none'})}
function fixVehicles(){const panel=document.querySelector('[data-road-runner-vehicles]');if(!panel)return;ensureFilters(panel);const s=load();s.unlockedVehicles=Array.isArray(s.unlockedVehicles)&&s.unlockedVehicles.length?s.unlockedVehicles:['hatchback'];panel.querySelectorAll('.roadRunnerVehicleCard').forEach(card=>{const btn=card.querySelector('button');const k=keyFrom(btn);if(!btn||!k)return;btn.disabled=false;const txt=btn.textContent||'';const cost=costFrom(txt);const unlocked=s.unlockedVehicles.includes(k);const selected=s.selectedVehicle===k;btn.onclick=null;if(!btn.dataset.v3){btn.dataset.v3='1';btn.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();const saveData=load();saveData.unlockedVehicles=Array.isArray(saveData.unlockedVehicles)&&saveData.unlockedVehicles.length?saveData.unlockedVehicles:['hatchback'];const c=costFrom(btn.textContent);if(saveData.unlockedVehicles.includes(k)){saveData.selectedVehicle=k;save(saveData);msg('Vehicle selected.');refresh();return}const miss=missing(c,saveData);if(miss){msg('Cannot unlock: '+miss);return}saveData.coins=(saveData.coins||0)-c.coins;saveData.parts=(saveData.parts||0)-c.parts;saveData.unlockedVehicles.push(k);saveData.selectedVehicle=k;save(saveData);msg('Vehicle unlocked and selected.');refresh()},{capture:true})}let note=card.querySelector('.rrWhyLocked');const miss=!unlocked?missing(cost,s):'';if(miss){if(!note){note=document.createElement('div');note.className='rrWhyLocked';card.appendChild(note)}note.textContent=miss}else note?.remove();if(selected)btn.textContent='Selected';else if(unlocked)btn.textContent='Select';else if(miss)btn.textContent='Unlock unavailable';});applyFilter(panel)}
function fixGarage(){document.querySelectorAll('[data-road-runner-garage] .roadRunnerUpgradeCard').forEach(card=>{const btn=card.querySelector('button');if(!btn)return;const k=keyFrom(btn);if(!k)return;btn.disabled=false;btn.onclick=null;if(!btn.dataset.v3){btn.dataset.v3='1';btn.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();const s=load();s.upgrades={...up0(),...(s.upgrades||{})};const lvl=s.upgrades[k]||1;const c=costFrom(card.textContent);const miss=missing(c,s);if(miss){msg('Cannot upgrade: '+miss);return}s.coins=(s.coins||0)-c.coins;s.parts=(s.parts||0)-c.parts;s.upgrades[k]=lvl+1;save(s);msg('Upgrade applied.');refresh()},{capture:true})}})}
function tick(){fixVehicles();fixGarage()}setInterval(tick,400);window.addEventListener('load',tick);document.addEventListener('click',()=>setTimeout(tick,60));
