const SPEED_SCALE=.55;
const BANDS=[['ZERO DMG',50,'rrRiskZero','no damage'],['SMALL',62,'rrRiskSmall','small risk'],['MINOR',74,'rrRiskMinor','minor wear'],['MODERATE',88,'rrRiskModerate','moderate wear'],['LOTS',104,'rrRiskLots','heavy wear'],['EPIC DMG',1/0,'rrRiskEpic','too fast']];
const GEARS=[{g:1,u:9,d:0,r:3.35},{g:2,u:18,d:6,r:2.30},{g:3,u:31,d:14,r:1.62},{g:4,u:48,d:25,r:1.15},{g:5,u:1/0,d:38,r:.82}];
let lastMeters=null,sampleMeters=null,sampleTime=null,lastFrame=null,targetKmh=0,showKmh=0,showRpm=850,gear=1,shiftAt=0;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
function meters(){const n=document.querySelector('#screen-race.active [data-rr-distance]');const m=String(n?.textContent||'').replace(/,/g,'').match(/([0-9.]+)/);return m?Number(m[1]):0;}
function band(kmh){return BANDS.find(x=>kmh<=x[1])||BANDS[BANDS.length-1];}
function gas(){return Boolean(document.querySelector('#screen-race.active [data-rr-control="gas"].active'));}
function brake(){return Boolean(document.querySelector('#screen-race.active [data-rr-control="brake"].active'));}
function panel(){const f=document.querySelector('#screen-race.active .roadRunnerGameFrame');if(!f)return null;let p=f.querySelector('[data-rr-telemetry]');if(p)return p;p=document.createElement('div');p.className='rrTelemetry';p.dataset.rrTelemetry='true';p.innerHTML=`<div class="rrTelemetryGauges"><div class="rrGaugeBox rrTelemetrySpeed"><b data-rr-speed-value>0</b><span>KM/H</span></div><div class="rrGaugeBox rrTelemetryRpm"><div><b data-rr-rpm-value>850</b><span>RPM</span><div class="rrRpmBar"><div data-rr-rpm-bar></div></div><small data-rr-gear-value>G1</small></div></div></div><div class="rrDamageRisk rrRiskZero" data-rr-damage-band>ZERO DMG</div><div class="rrDamageHelp" data-rr-damage-help>No damage &lt; 50 km/h</div>`;f.appendChild(p);return p;}
function sample(now){const live=window.__rrTelemetry;if(live&&typeof live.speedKmh==='number'){targetKmh=clamp(Math.abs(live.speedKmh),0,110);return targetKmh;}const m=meters();if(lastMeters!==null&&m<lastMeters){reset();sampleMeters=m;sampleTime=now;lastMeters=m;return 0;}lastMeters=m;if(sampleMeters===null||sampleTime===null){sampleMeters=m;sampleTime=now;return targetKmh;}const sec=(now-sampleTime)/1000;if(sec<.22)return targetKmh;const dm=Math.max(0,m-sampleMeters);const raw=clamp((dm/sec)*3.6*SPEED_SCALE,0,96);sampleMeters=m;sampleTime=now;targetKmh=dm===0?(gas()?Math.max(targetKmh*.975,showKmh*.965):Math.max(0,targetKmh-10*sec)):(targetKmh*.58+raw*.42);return targetKmh;}
function ramp(cur,t,dt,up,dn){const rate=t>=cur?up:dn;return cur+clamp(t-cur,-rate*dt,rate*dt);}
function shift(kmh,now){const g=GEARS[gear-1]||GEARS[0];if(kmh>g.u&&gear<GEARS.length){gear++;shiftAt=now;}else if(kmh<g.d&&gear>1){gear--;shiftAt=now;}}
function rpmTarget(kmh,now){const live=window.__rrTelemetry;if(live&&typeof live.rpm==='number')return clamp(live.rpm,760,6500);shift(kmh,now);const g=GEARS[gear-1]||GEARS[0];const throttle=gas()?720:0;const load=brake()?-260:0;const dip=now-shiftAt<210?-520:0;const idle=kmh<2&&!gas()?850:1020;return clamp(idle+kmh*g.r*43+throttle+load+dip,780,6300);}
function update(now){const dt=lastFrame?clamp((now-lastFrame)/1000,.016,.08):.016;lastFrame=now;const wanted=sample(now);showKmh=ramp(showKmh,wanted,dt,22,30);if(!gas()&&wanted<2)showKmh=ramp(showKmh,0,dt,13,20);showRpm=ramp(showRpm,rpmTarget(showKmh,now),dt,1250,1550);return{kmh:clamp(showKmh,0,110),rpm:clamp(showRpm,760,6600),gear};}
function tick(){const p=panel();if(!p){requestAnimationFrame(tick);return;}const s=update(performance.now());const live=window.__rrTelemetry||{};const kmh=Math.round(s.kmh),rpm=Math.round(s.rpm),riskSpeed=live.hazardSpeedKmh!=null?live.hazardSpeedKmh:kmh,b=band(riskSpeed);p.querySelector('[data-rr-speed-value]').textContent=String(kmh);p.querySelector('[data-rr-rpm-value]').textContent=String(rpm);p.querySelector('[data-rr-rpm-bar]').style.width=`${clamp(rpm/6300*100,0,100)}%`;p.querySelector('[data-rr-gear-value]').textContent=`G${s.gear}`;const risk=p.querySelector('[data-rr-damage-band]');risk.className=`rrDamageRisk ${b[2]}`;risk.textContent=live.damageLabel||b[0];const hazard=live.nextHazardMeters!=null?` • hazard ${live.nextHazardMeters}m`:'';p.querySelector('[data-rr-damage-help]').textContent=`${b[3]} • damage starts 50${hazard}`;requestAnimationFrame(tick);}
function reset(){lastMeters=null;sampleMeters=null;sampleTime=null;lastFrame=null;targetKmh=0;showKmh=0;showRpm=850;gear=1;shiftAt=performance.now();}
document.addEventListener('click',e=>{const t=e.target;if(t instanceof HTMLElement&&t.textContent?.toLowerCase().includes('restart'))reset();});
requestAnimationFrame(tick);
