const RR_SAVE = '365_canvas_road_runner_v4';
const MISSION_SAVE = '365_road_runner_mission_progress_v1';

const ROUTES = {
  track: { label: 'PH: Barangay Test Loop', unlock: 0 }, japan: { label: 'Japan: Touge Night Run', unlock: 450 }, china: { label: 'China: Great Wall Ridge', unlock: 900 }, thailand: { label: 'Thailand: Market Coast', unlock: 1300 }, india: { label: 'India: Monsoon Highway', unlock: 1800 }, uae: { label: 'UAE: Desert Express', unlock: 2300 }, egypt: { label: 'Egypt: Nile Desert Run', unlock: 2900 }, italy: { label: 'Italy: Coastal Sprint', unlock: 3500 }, usa: { label: 'USA: Route 365 Highway', unlock: 4300 }, brazil: { label: 'Brazil: Rainforest Rally', unlock: 5200 }, canada: { label: 'Canada: Northern Forest Run', unlock: 6100 }, australia: { label: 'Australia: Outback Sprint', unlock: 7100 }, germany: { label: 'Germany: Autobahn Test', unlock: 8200 }, uk: { label: 'UK: Rainy Country Road', unlock: 9300 }, mexico: { label: 'Mexico: Baja Dust Trail', unlock: 10500 }, southAfrica: { label: 'South Africa: Safari Ridge', unlock: 11800 }, korea: { label: 'Korea: Neon City Climb', unlock: 13200 }, indonesia: { label: 'Indonesia: Island Volcano Road', unlock: 14800 }, france: { label: 'France: Alpine Vineyard Pass', unlock: 16500 }, spain: { label: 'Spain: Mediterranean Rally', unlock: 18400 }
};

const VEHICLES = {
  hatchback:{coins:0,parts:0},greenCompact:{coins:180,parts:1},cityTaxi:{coins:260,parts:2},pickup:{coins:420,parts:4},rallyLite:{coins:640,parts:6},serviceVan:{coins:820,parts:8},desertRunner:{coins:1050,parts:11},offroad:{coins:1300,parts:14},exportVan:{coins:1650,parts:18},race:{coins:2050,parts:22},mountainCourier:{coins:2600,parts:28},superCoupe:{coins:3400,parts:36}
};

const UPGRADES = {
  engine:{label:'Engine',max:15,baseCoins:45,baseParts:0,growth:1.42,partsEvery:4}, tires:{label:'Tires',max:15,baseCoins:40,baseParts:0,growth:1.40,partsEvery:3}, fuelTank:{label:'Fuel Tank',max:15,baseCoins:55,baseParts:0,growth:1.45,partsEvery:3}, suspension:{label:'Suspension',max:15,baseCoins:45,baseParts:0,growth:1.42,partsEvery:3}, durability:{label:'Durability',max:15,baseCoins:60,baseParts:1,growth:1.50,partsEvery:2}, transmission:{label:'Transmission',max:10,baseCoins:95,baseParts:1,growth:1.55,partsEvery:2}, brakes:{label:'Brakes',max:10,baseCoins:70,baseParts:0,growth:1.46,partsEvery:3}, repairKit:{label:'Repair Kit',max:10,baseCoins:85,baseParts:1,growth:1.48,partsEvery:2}
};

const MISSION_DEFS = [
  { id:'daily-run-1', type:'daily', label:'Daily Warmup', desc:'Finish or fail 1 route today.', metric:'runs', target:1, coins:90, parts:1, tools:0, unlock:0 },
  { id:'daily-distance-2500', type:'daily', label:'Daily Distance', desc:'Drive 2500m today.', metric:'distance', target:2500, coins:130, parts:2, tools:0, unlock:0 },
  { id:'daily-parts-10', type:'daily', label:'Daily Parts Hunt', desc:'Collect 10 parts today.', metric:'parts', target:10, coins:80, parts:3, tools:0, unlock:900 },
  { id:'daily-tools-3', type:'daily', label:'Daily Tool Run', desc:'Collect 3 tools today.', metric:'tools', target:3, coins:70, parts:1, tools:1, unlock:1300 },
  { id:'weekly-runs-10', type:'weekly', label:'Weekly Route Streak', desc:'Complete 10 route attempts this week.', metric:'runs', target:10, coins:850, parts:8, tools:2, unlock:0 },
  { id:'weekly-distance-25000', type:'weekly', label:'Weekly World Tour', desc:'Drive 25,000m this week.', metric:'distance', target:25000, coins:1200, parts:14, tools:2, unlock:2300 },
  { id:'weekly-coins-2500', type:'weekly', label:'Weekly Coin Haul', desc:'Collect 2,500 run coins this week.', metric:'coins', target:2500, coins:900, parts:10, tools:2, unlock:3500 },
  { id:'progress-best-5000', type:'progress', label:'Open Brazil Tier', desc:'Reach 5,000m best distance.', metric:'bestDistance', target:5000, coins:700, parts:10, tools:1, unlock:0 },
  { id:'progress-best-10000', type:'progress', label:'International Driver', desc:'Reach 10,000m best distance.', metric:'bestDistance', target:10000, coins:1400, parts:18, tools:3, unlock:5000 },
  { id:'progress-best-18000', type:'progress', label:'World Route License', desc:'Reach 18,000m best distance.', metric:'bestDistance', target:18000, coins:2600, parts:30, tools:5, unlock:10000 }
];

function loadRR(){try{return JSON.parse(localStorage.getItem(RR_SAVE)||'{}')}catch{return{}}}
function saveRR(s){localStorage.setItem(RR_SAVE,JSON.stringify(s))}
function todayKey(){return new Date().toISOString().slice(0,10)}
function weekKey(){const d=new Date();const oneJan=new Date(d.getFullYear(),0,1);const week=Math.ceil((((d-oneJan)/86400000)+oneJan.getDay()+1)/7);return `${d.getFullYear()}-W${week}`}
function loadM(){try{return JSON.parse(localStorage.getItem(MISSION_SAVE)||'{}')}catch{return{}}}
function saveM(s){localStorage.setItem(MISSION_SAVE,JSON.stringify(s))}
function cost(key,level){const u=UPGRADES[key];return{coins:Math.round(u.baseCoins*Math.pow(u.growth,level-1)),parts:u.baseParts+Math.floor(level/u.partsEvery)}}
function missingText(need,s){const c=Math.max(0,(need.coins||0)-(s.coins||0));const p=Math.max(0,(need.parts||0)-(s.parts||0));return c||p?`Need ${c} coins / ${p} parts`:''}
function toast(msg){let t=document.querySelector('.rrProgressToast');if(!t){t=document.createElement('div');t.className='rrProgressToast';document.body.appendChild(t)}t.textContent=msg;t.classList.add('show');clearTimeout(t._timer);t._timer=setTimeout(()=>t.classList.remove('show'),2200)}

function addReasons(){const s=loadRR();document.querySelectorAll('.roadRunnerVehicleCard').forEach(card=>{if(card.querySelector('.rrWhyLocked'))return;const btn=card.querySelector('button');if(!btn||!btn.disabled||!/Locked/i.test(btn.textContent||''))return;const key=(btn.getAttribute('onclick')||'').match(/'([^']+)'/)?.[1];const need=VEHICLES[key];if(!need)return;const note=document.createElement('div');note.className='rrWhyLocked';note.textContent=missingText(need,s)||'Locked';card.appendChild(note)});document.querySelectorAll('.roadRunnerUpgradeCard').forEach(card=>{if(card.querySelector('.rrWhyLocked'))return;const btn=card.querySelector('button');if(!btn||!btn.disabled)return;const key=(btn.getAttribute('onclick')||'').match(/'([^']+)'/)?.[1];const u=UPGRADES[key];if(!u)return;const level=Number((card.querySelector('h4')?.textContent||'').match(/Lv\.(\d+)/)?.[1]||1);const note=document.createElement('div');note.className='rrWhyLocked';note.textContent=level>=u.max?'Maxed':missingText(cost(key,level),s);card.appendChild(note)});}

function wireRoutes(){document.querySelectorAll('.rrRouteCard[data-route-key]').forEach(card=>{if(card.dataset.routeWired)return;card.dataset.routeWired='true';card.tabIndex=0;card.addEventListener('click',()=>{const key=card.dataset.routeKey;const s=loadRR();const r=ROUTES[key];if(!r)return;const left=Math.max(0,r.unlock-(s.bestDistance||0));if(left>0){toast(`Route locked: drive ${left}m more best distance.`);return}window.setHillRoute?.(key);toast(`Selected route: ${r.label}`);document.querySelector('[data-racer-tab="drive"]')?.click();});});}

function patchActions(){if(window.__rrProgressionActionsPatched)return;window.__rrProgressionActionsPatched=true;const oldUnlock=window.unlockRoadRunnerVehicle;window.unlockRoadRunnerVehicle=(key)=>{const s=loadRR();const need=VEHICLES[key];if(!need){toast('Vehicle not found.');return}const miss=missingText(need,s);if(miss){toast(`Cannot unlock: ${miss}`);return}oldUnlock?.(key);toast('Vehicle unlocked and selected.');setTimeout(addReasons,200)};const oldSelect=window.selectRoadRunnerVehicle;window.selectRoadRunnerVehicle=(key)=>{const s=loadRR();if(!(s.unlockedVehicles||['hatchback']).includes(key)){toast('Vehicle locked. Unlock it first.');return}oldSelect?.(key);toast('Vehicle selected.');};const oldBuy=window.buyRoadRunnerUpgrade;window.buyRoadRunnerUpgrade=(key)=>{const s=loadRR();const u=UPGRADES[key];if(!u){toast('Upgrade not found.');return}const level=(s.upgrades||{})[key]||1;if(level>=u.max){toast(`${u.label} is maxed.`);return}const miss=missingText(cost(key,level),s);if(miss){toast(`Cannot upgrade: ${miss}`);return}oldBuy?.(key);toast(`${u.label} upgraded.`);setTimeout(addReasons,200)};}

function recordRunFromPanel(){const panel=document.querySelector('#screen-race.active [data-rr-end-panel]:not([hidden])');if(!panel||panel.dataset.missionRecorded)return;const text=panel.textContent||'';const dist=Number(text.match(/(\d+)m/)?.[1]||0);const coins=Number(text.match(/Run Coins\s*\+(\d+)|\+(\d+) coins/)?.[1]||text.match(/Run Coins\s*\+(\d+)|\+(\d+) coins/)?.[2]||0);const parts=Number(text.match(/Parts\s*\+(\d+)|\+(\d+) parts/)?.[1]||text.match(/Parts\s*\+(\d+)|\+(\d+) parts/)?.[2]||0);const tools=Number(text.match(/Tools\s*\+(\d+)|\+(\d+) tools/)?.[1]||text.match(/Tools\s*\+(\d+)|\+(\d+) tools/)?.[2]||0);if(!dist&&!coins&&!parts&&!tools)return;const m=loadM();const day=todayKey(),week=weekKey();if(m.dayKey!==day)m.daily={runs:0,distance:0,coins:0,parts:0,tools:0,claimed:[]};if(m.weekKey!==week)m.weekly={runs:0,distance:0,coins:0,parts:0,tools:0,claimed:[]};m.dayKey=day;m.weekKey=week;m.progress=m.progress||{claimed:[]};m.daily.runs=(m.daily.runs||0)+1;m.daily.distance=(m.daily.distance||0)+dist;m.daily.coins=(m.daily.coins||0)+coins;m.daily.parts=(m.daily.parts||0)+parts;m.daily.tools=(m.daily.tools||0)+tools;m.weekly.runs=(m.weekly.runs||0)+1;m.weekly.distance=(m.weekly.distance||0)+dist;m.weekly.coins=(m.weekly.coins||0)+coins;m.weekly.parts=(m.weekly.parts||0)+parts;m.weekly.tools=(m.weekly.tools||0)+tools;saveM(m);panel.dataset.missionRecorded='true';renderMissions();}

function missionProgress(def,rr,m){const bucket=def.type==='daily'?m.daily:def.type==='weekly'?m.weekly:m.progress;const val=def.metric==='bestDistance'?(rr.bestDistance||0):(bucket?.[def.metric]||0);return Math.min(def.target,val)}
function claimed(def,m){const arr=def.type==='daily'?m.daily?.claimed:def.type==='weekly'?m.weekly?.claimed:m.progress?.claimed;return (arr||[]).includes(def.id)}
function claim(def){const rr=loadRR(),m=loadM();const prog=missionProgress(def,rr,m);if(prog<def.target){toast('Mission not complete yet.');return}const arr=def.type==='daily'?m.daily.claimed:def.type==='weekly'?m.weekly.claimed:m.progress.claimed;if(arr.includes(def.id)){toast('Reward already claimed.');return}arr.push(def.id);rr.coins=(rr.coins||0)+def.coins;rr.parts=(rr.parts||0)+def.parts;rr.tools=(rr.tools||0)+def.tools;saveRR(rr);saveM(m);toast(`Claimed: +${def.coins} coins, +${def.parts} parts, +${def.tools} tools`);renderMissions();}

function renderMissions(){const page=document.querySelector('[data-racer-page="missions"]');if(!page)return;const rr=loadRR(),m=loadM();if(m.dayKey!==todayKey()){m.dayKey=todayKey();m.daily={runs:0,distance:0,coins:0,parts:0,tools:0,claimed:[]}}if(m.weekKey!==weekKey()){m.weekKey=weekKey();m.weekly={runs:0,distance:0,coins:0,parts:0,tools:0,claimed:[]}}m.progress=m.progress||{claimed:[]};saveM(m);const best=rr.bestDistance||0;page.innerHTML=`<section class="rrMissionBoard"><div class="rrProgressTitle"><h3>Daily / Weekly Missions</h3><span>Daily ${m.dayKey} • Weekly ${m.weekKey}</span></div><div class="rrProgressWallet"><span>🪙 ${Math.floor(rr.coins||0)}</span><span>🔩 ${Math.floor(rr.parts||0)}</span><span>🧰 ${Math.floor(rr.tools||0)}</span><span>🏁 Best ${Math.floor(best)}m</span></div>${MISSION_DEFS.filter(x=>best>=x.unlock).map(def=>{const p=missionProgress(def,rr,m),pct=Math.min(100,p/def.target*100),isClaimed=claimed(def,m),ready=p>=def.target&&!isClaimed;return `<article class="rrMissionCard ${ready?'ready':''} ${isClaimed?'claimed':''}"><div><b>${def.type.toUpperCase()} • ${def.label}</b><p>${def.desc}</p><small>Reward: ${def.coins}C / ${def.parts}P / ${def.tools}T</small><div class="rrUnlockBar"><i style="width:${pct}%"></i></div><span>${Math.floor(p)} / ${def.target}</span></div><button type="button" data-claim-mission="${def.id}" ${ready?'':'disabled'}>${isClaimed?'Claimed':ready?'Claim':'Locked'}</button></article>`}).join('')}</section>`;page.querySelectorAll('[data-claim-mission]').forEach(btn=>btn.addEventListener('click',()=>{const def=MISSION_DEFS.find(x=>x.id===btn.dataset.claimMission);if(def)claim(def)}));}

function tick(){patchActions();wireRoutes();addReasons();recordRunFromPanel();if(document.querySelector('[data-racer-page="missions"]'))renderMissions()}
setInterval(tick,1000);document.addEventListener('click',()=>setTimeout(tick,50));window.addEventListener('load',tick);

const rrV2Style=document.createElement('link');rrV2Style.rel='stylesheet';rrV2Style.href='/roadRunnerResultClose.css';document.head.appendChild(rrV2Style);
import('./roadRunnerProgressionRepairV2.js');
import('./roadRunnerVehicleGarageFixV3.js');
